import { Command } from 'commander';
import chalk from 'chalk';
import ora from 'ora';
import { existsSync, readFileSync, writeFileSync, mkdirSync, readdirSync } from 'fs';
import { resolve, join, relative, dirname } from 'path';
import { loadConfig, getStrings, escapeHtml, extractFrontmatter } from '@codedocs/core';
import type { Locale } from '@codedocs/core';
import { getCliStrings, t, initLocale } from '../i18n.js';
import { Marked } from 'marked';
import { runSubprocess } from '../utils/run-subprocess.js';

export const buildCommand = new Command('build')
  .description('Build production-ready documentation site')
  .option('-c, --config <path>', 'Path to config file', 'codedocs.config.ts')
  .option('--skip-analyze', 'Skip analysis step')
  .option('--skip-generate', 'Skip generation step')
  .option('--verbose', 'Show detailed build output')
  .option('--docs-dir <path>', 'Input docs directory', './docs-output')
  .option('-o, --output <path>', 'Output directory for built site', './dist')
  .action(async (options) => {
    const s = getCliStrings().cli;
    console.log(chalk.bold.cyan(`\n🏗️  ${s.buildTitle}\n`));

    try {
      // Load config
      const configPath = resolve(process.cwd(), options.config);
      if (!existsSync(configPath)) {
        console.error(chalk.red(`${s.configNotFound}: ${options.config}\n`));
        process.exit(1);
      }

      const config = await loadConfig(configPath);
      initLocale(config.docs?.locale);
      const strings = getCliStrings().cli;
      const outDir = options.output;

      // Step 1: Analyze
      if (!options.skipAnalyze) {
        await runSubprocess('analyze', ['analyze', '-c', options.config], { verbose: options.verbose });
      } else {
        console.log(chalk.dim(`⊘ ${strings.skippingAnalysis}\n`));
      }

      // Step 2: Generate
      if (!options.skipGenerate) {
        await runSubprocess('generate', ['generate', '-c', options.config], { verbose: options.verbose });
      } else {
        console.log(chalk.dim(`⊘ ${strings.skippingGeneration}\n`));
      }

      // Step 3: Build static HTML site
      console.log(chalk.cyan(strings.buildingSite));
      const spinner = ora(strings.buildingSite).start();
      await buildStaticSite(options.docsDir, outDir, config);
      spinner.succeed(strings.buildComplete);

      // Summary
      console.log(chalk.green(`\n✓ ${strings.buildComplete}\n`));
      console.log(chalk.dim(`  ${t(strings.outputDirectory, { dir: outDir })}`));
      console.log(chalk.cyan(`\n${strings.nextSteps}`));
      console.log(chalk.dim(`  - ${t(strings.deployHint, { dir: outDir })}`));
      console.log(chalk.dim(`  - ${strings.previewLocalHint}\n`));
    } catch (error) {
      console.error(chalk.red(`\n✗ ${getCliStrings().cli.buildFailed}\n`));
      console.error(chalk.red((error as Error).message));
      process.exit(1);
    }
  });

async function buildStaticSite(docsDir: string, outDir: string, config: any): Promise<void> {
  const docsPath = resolve(process.cwd(), docsDir);
  const distPath = resolve(process.cwd(), outDir);

  if (!existsSync(docsPath)) {
    throw new Error(`Documentation directory not found: ${docsDir}. Run "codedocs generate" first.`);
  }

  // Create dist directory
  if (!existsSync(distPath)) {
    mkdirSync(distPath, { recursive: true });
  }

  // Collect all markdown files
  const mdFiles = collectMarkdownFiles(docsPath);

  if (mdFiles.length === 0) {
    throw new Error(`No markdown files found in ${docsDir}`);
  }

  // Get locale strings
  const locale = (config.docs?.locale || 'en') as Locale;
  const s = getStrings(locale);

  // Parse markdown files and build navigation
  const pages = mdFiles.map(filePath => {
    const raw = readFileSync(filePath, 'utf-8');
    const { meta, body } = extractFrontmatter(raw);
    const relPath = relative(docsPath, filePath);
    const slug = relPath.replace(/\.md$/, '');
    const title = meta.title || slug.split('/').pop() || 'Untitled';
    const position = meta.sidebar_position ? Number(meta.sidebar_position) : 999;
    return { filePath, relPath, slug, title, body, meta, position };
  });

  // Sort pages by sidebar position
  pages.sort((a, b) => a.position - b.position);

  // Load sidebar structure from _sidebar.json (generated by SidebarGenerator)
  const sidebarJsonPath = join(docsPath, '_sidebar.json');
  const sidebarStructure = existsSync(sidebarJsonPath)
    ? JSON.parse(readFileSync(sidebarJsonPath, 'utf-8'))
    : null;

  // Initialize marked with custom renderer for mermaid
  const marked = new Marked({
    renderer: {
      code(token) {
        if (token.lang === 'mermaid') {
          const encoded = Buffer.from(token.text, 'utf-8').toString('base64');
          return `<div class="mermaid-wrapper"><div class="mermaid-toolbar"><button class="mermaid-copy-btn" data-source="${encoded}" title="Copy code"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg></button><button class="mermaid-expand-btn" data-source="${encoded}" title="Expand"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M15 3h6v6M9 21H3v-6M21 3l-7 7M3 21l7-7"/></svg></button></div><div class="mermaid">${token.text}</div></div>`;
        }
        return `<pre><code class="language-${token.lang || ''}">${escapeHtml(token.text)}</code></pre>`;
      }
    }
  });

  // Get project name from config
  const projectName = config.name || config.docs?.title || 'Documentation';

  // Collect all known slugs for link rewriting
  const knownSlugs = new Set(pages.map(p => p.slug));

  // Generate HTML for each page
  for (const page of pages) {
    const htmlContent = await marked.parse(page.body);
    // Rewrite internal .md links to .html and fix directory links
    const rewrittenContent = rewriteInternalLinks(htmlContent, knownSlugs);
    const sanitizedContent = rewrittenContent.replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '').replace(/\bon\w+\s*=/gi, 'data-removed-handler=');
    const contentWithIds = addHeadingIds(sanitizedContent);
    const tocHeadings = extractTocHeadings(contentWithIds);
    const basePrefix = getRelativePrefix(page.slug);
    const navItems = sidebarStructure
      ? buildTopNav(sidebarStructure, basePrefix, page.slug, s)
      : pages.map(p => ({ label: p.title, href: `${basePrefix}${p.slug}.html`, active: p.slug === page.slug }));
    const htmlPage = generateHtmlPage({
      title: page.title,
      projectName,
      content: contentWithIds,
      navItems,
      tocHeadings,
      currentSlug: page.slug,
      pageId: page.slug,
      locale,
      s,
      basePrefix,
      sidebarStructure: sidebarStructure || [],
    });

    const outFile = join(distPath, `${page.slug}.html`);
    const outFileDir = dirname(outFile);
    if (!existsSync(outFileDir)) {
      mkdirSync(outFileDir, { recursive: true });
    }
    writeFileSync(outFile, htmlPage, 'utf-8');
  }

  // Generate index.html that redirects to the index page or first page
  const indexPage = pages.find(p => p.slug === 'index') || pages[0];
  if (indexPage && indexPage.slug !== 'index') {
    // Create redirect index.html
    writeFileSync(
      join(distPath, 'index.html'),
      `<!DOCTYPE html><meta http-equiv="refresh" content="0;url=./${indexPage.slug}.html">`,
      'utf-8'
    );
  }

  // Write CSS file
  const assetsDir = join(distPath, 'assets');
  if (!existsSync(assetsDir)) {
    mkdirSync(assetsDir, { recursive: true });
  }
  writeFileSync(join(assetsDir, 'style.css'), getStylesheet(), 'utf-8');
}

function collectMarkdownFiles(dir: string): string[] {
  const files: string[] = [];
  const entries = readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...collectMarkdownFiles(fullPath));
    } else if (entry.name.endsWith('.md')) {
      files.push(fullPath);
    }
  }
  return files;
}

function getRelativePrefix(slug: string): string {
  const depth = (slug.match(/\//g) || []).length;
  return depth === 0 ? './' : '../'.repeat(depth);
}

// ── Navigation / TOC types and helpers ──

interface NavItem {
  label: string;
  href: string;
  active: boolean;
  children?: NavItem[];
}

interface TocHeading {
  id: string;
  text: string;
  level: number;
}

function buildTopNav(items: any[], basePrefix: string, currentSlug: string, s: any): NavItem[] {
  const navItems: NavItem[] = [];
  for (const item of items) {
    if (item.type === 'category' && item.items) {
      const firstChild = item.items[0];
      const isActive = item.items.some((child: any) => child.id === currentSlug);
      navItems.push({
        label: item.label,
        href: firstChild ? `${basePrefix}${firstChild.id}.html` : '#',
        active: isActive,
      });
    } else {
      navItems.push({
        label: item.label,
        href: `${basePrefix}${item.id}.html`,
        active: item.id === currentSlug,
      });
    }
  }
  // Add Memo nav item
  navItems.push({
    label: s.nav?.memo || 'Memo',
    href: `${basePrefix}memo.html`,
    active: currentSlug === 'memo',
  });
  return navItems;
}

function addHeadingIds(html: string): string {
  const usedIds = new Set<string>();
  return html.replace(/<(h[23])>(.*?)<\/\1>/g, (_match, tag, text) => {
    const plainText = text.replace(/<[^>]+>/g, '').trim();
    let id = plainText
      .toLowerCase()
      .replace(/[^\w\s-\u3131-\uD79D]/g, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-');
    if (!id) id = 'heading';
    let uniqueId = id;
    let counter = 1;
    while (usedIds.has(uniqueId)) {
      uniqueId = `${id}-${counter++}`;
    }
    usedIds.add(uniqueId);
    return `<${tag} id="${uniqueId}">${text}</${tag}>`;
  });
}

function extractTocHeadings(html: string): TocHeading[] {
  const headings: TocHeading[] = [];
  const regex = /<(h[23])\s+id="([^"]*)">(.*?)<\/\1>/g;
  let match;
  while ((match = regex.exec(html)) !== null) {
    const level = parseInt(match[1].charAt(1));
    const id = match[2];
    const text = match[3].replace(/<[^>]+>/g, '').trim();
    headings.push({ id, text, level });
  }
  return headings;
}

function buildNavHtml(navItems: NavItem[]): string {
  return navItems.map(item =>
    `<li class="top-nav-item"><a href="${item.href}" class="top-nav-link${item.active ? ' active' : ''}">${escapeHtml(item.label)}</a></li>`
  ).join('\n');
}

function buildTocHtml(headings: TocHeading[], s: any): string {
  if (headings.length === 0) return '';
  const items = headings.map(h =>
    `<li class="toc-item toc-h${h.level}"><a href="#${escapeHtml(h.id)}">${escapeHtml(h.text)}</a></li>`
  ).join('\n');
  return `<aside class="toc-sidebar">
    <div class="toc-container">
      <div class="toc-title">${escapeHtml(s.toc.onThisPage)}</div>
      <ul class="toc-list">${items}</ul>
    </div>
  </aside>`;
}

function buildLeftSidebar(sidebarStructure: any[], currentSlug: string, basePrefix: string, s: any): string {
  if (currentSlug === 'index' || currentSlug === 'memo') return '';

  // Find which section the current page belongs to
  var activeSection: any = null;
  for (var i = 0; i < sidebarStructure.length; i++) {
    var item = sidebarStructure[i];
    if (item.type === 'category' && item.items) {
      for (var j = 0; j < item.items.length; j++) {
        if (item.items[j].id === currentSlug) {
          activeSection = item;
          break;
        }
      }
      if (activeSection) break;
    } else if (item.id === currentSlug) {
      // Top-level doc item (overview, architecture) -- no sidebar needed
      return '';
    }
  }

  if (!activeSection || !activeSection.items) return '';

  var listItems = activeSection.items.map(function (child: any) {
    var isActive = child.id === currentSlug;
    return '<li class="left-sidebar-item' + (isActive ? ' active' : '') + '"><a href="' + basePrefix + child.id + '.html">' + escapeHtml(child.label) + '</a></li>';
  }).join('\n');

  return '<aside class="left-sidebar">\n  <div class="left-sidebar-container">\n    <div class="left-sidebar-title">' + escapeHtml(activeSection.label) + '</div>\n    <ul class="left-sidebar-list">\n' + listItems + '\n    </ul>\n  </div>\n</aside>';
}

function buildBreadcrumb(sidebarStructure: any[], currentSlug: string, basePrefix: string, s: any): string {
  if (currentSlug === 'index') return '';
  if (currentSlug === 'memo') return '';

  var homeIcon = '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg>';
  var homeLink = '<a href="' + basePrefix + 'index.html" class="breadcrumb-item breadcrumb-home">' + homeIcon + '</a>';
  var sep = '<span class="breadcrumb-sep">/</span>';

  // Find which section the current page belongs to
  for (var i = 0; i < sidebarStructure.length; i++) {
    var item = sidebarStructure[i];
    if (item.type === 'category' && item.items) {
      for (var j = 0; j < item.items.length; j++) {
        if (item.items[j].id === currentSlug) {
          var firstChildHref = basePrefix + item.items[0].id + '.html';
          var sectionLink = '<a href="' + firstChildHref + '" class="breadcrumb-item">' + escapeHtml(item.label) + '</a>';
          var currentLabel = '<span class="breadcrumb-item breadcrumb-current">' + escapeHtml(item.items[j].label) + '</span>';
          return '<nav class="breadcrumb" aria-label="Breadcrumb">' + homeLink + sep + sectionLink + sep + currentLabel + '</nav>';
        }
      }
    } else if (item.id === currentSlug) {
      // Top-level doc (overview, architecture, changelog)
      var currentLabelTop = '<span class="breadcrumb-item breadcrumb-current">' + escapeHtml(item.label) + '</span>';
      return '<nav class="breadcrumb" aria-label="Breadcrumb">' + homeLink + sep + currentLabelTop + '</nav>';
    }
  }

  // Fallback: just show Home
  return '<nav class="breadcrumb" aria-label="Breadcrumb">' + homeLink + '</nav>';
}

function getSectionIcon(label: string): string {
  var lower = label.toLowerCase();
  if (lower.includes('overview') || lower.includes('개요') || lower.includes('概要') || lower.includes('概述')) {
    return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="4" rx="1"/><rect x="14" y="10" width="7" height="11" rx="1"/><rect x="3" y="13" width="7" height="8" rx="1"/></svg>';
  }
  if (lower.includes('api') || lower.includes('endpoint')) {
    return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/></svg>';
  }
  if (lower.includes('component') || lower.includes('컴포넌트') || lower.includes('组件')) {
    return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 2l-2 7H3l6 4.5L7 21l5-3.5L17 21l-2-7.5L21 9h-7z"/></svg>';
  }
  if (lower.includes('hook') || lower.includes('service') || lower.includes('훅') || lower.includes('钩子')) {
    return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/></svg>';
  }
  if (lower.includes('architect') || lower.includes('아키텍처') || lower.includes('架构')) {
    return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="5" r="3"/><circle cx="5" cy="19" r="3"/><circle cx="19" cy="19" r="3"/><line x1="12" y1="8" x2="5" y2="16"/><line x1="12" y1="8" x2="19" y2="16"/></svg>';
  }
  if (lower.includes('changelog') || lower.includes('변경') || lower.includes('更新') || lower.includes('履歴')) {
    return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>';
  }
  if (lower.includes('memo') || lower.includes('메모') || lower.includes('备忘')) {
    return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 20h9"/><path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"/></svg>';
  }
  if (lower.includes('data') || lower.includes('model') || lower.includes('entity') || lower.includes('엔티티') || lower.includes('实体')) {
    return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M21 12c0 1.66-4 3-9 3s-9-1.34-9-3"/><path d="M3 5v14c0 1.66 4 3 9 3s9-1.34 9-3V5"/></svg>';
  }
  // Default: document icon
  return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/></svg>';
}

function getSectionDescription(label: string, s: any): string {
  var lower = label.toLowerCase();
  var desc = s.home?.sectionDesc || {};
  if (lower.includes('overview') || lower.includes('개요') || lower.includes('概要') || lower.includes('概述')) return desc.overview || 'Project summary, statistics, and quick links';
  if (lower.includes('api') || lower.includes('endpoint')) return desc.api || 'REST & GraphQL endpoint documentation';
  if (lower.includes('component') || lower.includes('컴포넌트') || lower.includes('组件')) return desc.components || 'UI component props and usage';
  if (lower.includes('hook') || lower.includes('service') || lower.includes('훅') || lower.includes('钩子')) return desc.hooks || 'Custom hooks and service layer';
  if (lower.includes('architect') || lower.includes('아키텍처') || lower.includes('架构')) return desc.architecture || 'Dependency graphs and system overview';
  if (lower.includes('changelog') || lower.includes('변경') || lower.includes('更新') || lower.includes('履歴')) return desc.changelog || 'Version history and changes';
  if (lower.includes('memo') || lower.includes('메모') || lower.includes('备忘')) return desc.memo || 'Team notes and annotations';
  if (lower.includes('data') || lower.includes('model') || lower.includes('entity')) return desc.api || 'Data model documentation';
  return '';
}

function buildDashboardContent(sidebarStructure: any[], basePrefix: string, projectName: string, s: any): string {
  var cards = '';
  for (var i = 0; i < sidebarStructure.length; i++) {
    var item = sidebarStructure[i];
    var href: string;
    var label: string;
    if (item.type === 'category' && item.items && item.items.length > 0) {
      href = basePrefix + item.items[0].id + '.html';
      label = item.label;
    } else {
      href = basePrefix + item.id + '.html';
      label = item.label;
    }
    var icon = getSectionIcon(label);
    var description = getSectionDescription(label, s);
    cards += '<a href="' + href + '" class="dashboard-card"><div class="dashboard-card-icon">' + icon + '</div><div class="dashboard-card-info"><h3>' + escapeHtml(label) + '</h3><p>' + escapeHtml(description) + '</p></div></a>\n';
  }
  // Add Memo card
  var memoIcon = getSectionIcon('memo');
  var memoDesc = getSectionDescription('memo', s);
  var memoLabel = s.nav?.memo || 'Memo';
  cards += '<a href="' + basePrefix + 'memo.html" class="dashboard-card"><div class="dashboard-card-icon">' + memoIcon + '</div><div class="dashboard-card-info"><h3>' + escapeHtml(memoLabel) + '</h3><p>' + escapeHtml(memoDesc) + '</p></div></a>\n';

  var title = projectName;
  var subtitle = s.home?.subtitle || 'Explore your project documentation';

  return '<div class="dashboard"><div class="dashboard-header"><h1 class="dashboard-title">' + escapeHtml(title) + '</h1><p class="dashboard-subtitle">' + escapeHtml(subtitle) + '</p></div><div class="dashboard-grid">' + cards + '</div></div>';
}

function buildMemoPageContent(s: any): string {
  var memoS = s.memoPage || {};
  var memoCommon = s.memo || {};
  var title = memoS.title || 'Memo Manager';
  var description = memoS.description || '';
  var exportLabel = memoCommon.exportAll || 'Export JSON';
  var copyLabel = memoS.copyJson || 'Copy JSON';
  var deleteAllLabel = memoS.deleteAll || 'Delete All';
  var filterAllLabel = memoS.filterAll || 'All';
  var importLabel = memoCommon.import || 'Import';
  var catImportant = memoCommon.important || 'Important';
  var catAdd = memoCommon.add || 'Add';
  var catModify = memoCommon.modify || 'Modify';
  var catDelete = memoCommon.delete || 'Delete';
  var catOther = memoCommon.other || 'Other';
  var totalCountTpl = memoS.totalCount || 'Total: {{n}} memos';
  var noMemos = memoS.noMemos || 'No memos yet. Add memos from any documentation page.';
  var confirmDeleteAll = memoS.confirmDeleteAll || 'Are you sure you want to delete all memos? This cannot be undone.';
  var copiedLabel = memoS.copied || 'Copied!';

  return '<div class="memo-page">' +
    '<div class="memo-page-header">' +
      '<h1>' + escapeHtml(title) + '</h1>' +
      '<p class="memo-page-desc">' + escapeHtml(description) + '</p>' +
    '</div>' +
    '<div class="memo-page-actions">' +
      '<button class="memo-page-action-btn" id="memoPageExport"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg> ' + escapeHtml(exportLabel) + '</button>' +
      '<button class="memo-page-action-btn" id="memoPageImport"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/></svg> ' + escapeHtml(importLabel) + '</button>' +
      '<input type="file" id="memoPageFileInput" accept=".json" style="display:none">' +
      '<button class="memo-page-action-btn" id="memoPageCopy"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg> ' + escapeHtml(copyLabel) + '</button>' +
      '<button class="memo-page-action-btn memo-page-danger-btn" id="memoPageDeleteAll"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg> ' + escapeHtml(deleteAllLabel) + '</button>' +
    '</div>' +
    '<div class="memo-page-filters">' +
      '<button class="memo-page-filter-btn active" data-filter="all">' + escapeHtml(filterAllLabel) + '</button>' +
      '<button class="memo-page-filter-btn" data-filter="important">! ' + escapeHtml(catImportant) + '</button>' +
      '<button class="memo-page-filter-btn" data-filter="add">+ ' + escapeHtml(catAdd) + '</button>' +
      '<button class="memo-page-filter-btn" data-filter="modify">~ ' + escapeHtml(catModify) + '</button>' +
      '<button class="memo-page-filter-btn" data-filter="delete">- ' + escapeHtml(catDelete) + '</button>' +
      '<button class="memo-page-filter-btn" data-filter="other">? ' + escapeHtml(catOther) + '</button>' +
    '</div>' +
    '<div class="memo-page-count" id="memoPageCount"></div>' +
    '<div class="memo-page-list" id="memoPageList"></div>' +
  '</div>' +
  '<script>' +
  '(function() {' +
    'var STORAGE_KEY = "codedocs-memos";' +
    'var CATEGORIES = {important:"!",add:"+",modify:"~","delete":"-",other:"?"};' +
    'var currentFilter = "all";' +
    'var confirmMsg = ' + JSON.stringify(confirmDeleteAll) + ';' +
    'var copiedMsg = ' + JSON.stringify(copiedLabel) + ';' +
    'var totalTpl = ' + JSON.stringify(totalCountTpl) + ';' +
    'var noMemosMsg = ' + JSON.stringify(noMemos) + ';' +
    'function loadAll() { try { var s = localStorage.getItem(STORAGE_KEY); return s ? JSON.parse(s) : []; } catch(e) { return []; } }' +
    'function saveAll(m) { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(m)); } catch(e) {} }' +
    'function formatTs(iso) { var d = new Date(iso); return d.toLocaleString(undefined, {year:"numeric",month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}); }' +
    'function render() {' +
      'var all = loadAll();' +
      'var filtered = currentFilter === "all" ? all : all.filter(function(m) { return m.category === currentFilter; });' +
      'filtered.sort(function(a,b) { return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime(); });' +
      'var countEl = document.getElementById("memoPageCount");' +
      'countEl.textContent = totalTpl.replace("{{n}}", String(filtered.length));' +
      'var list = document.getElementById("memoPageList");' +
      'list.innerHTML = "";' +
      'if (filtered.length === 0) { list.innerHTML = "<div class=\\"memo-page-empty\\">" + noMemosMsg + "</div>"; return; }' +
      'for (var i = 0; i < filtered.length; i++) {' +
        '(function(memo) {' +
          'var item = document.createElement("div");' +
          'item.className = "memo-page-item";' +
          'item.style.borderLeft = "4px solid " + (memo.color || "#fff9c4");' +
          'var catIcon = CATEGORIES[memo.category] || "?";' +
          'item.innerHTML = "<span class=\\"memo-page-item-cat\\">" + catIcon + "</span>" +' +
            '"<div class=\\"memo-page-item-info\\">" +' +
              '"<div class=\\"memo-page-item-target\\">" + (memo.target || "(no target)") + "</div>" +' +
              '"<div class=\\"memo-page-item-content\\">" + ((memo.content || "").length > 100 ? (memo.content || "").slice(0,100) + "..." : (memo.content || "")) + "</div>" +' +
              '"<div class=\\"memo-page-item-meta\\">" + (memo.pageTitle || "") + " &middot; " + formatTs(memo.createdAt) + "</div>" +' +
            '"</div>";' +
          'item.addEventListener("click", function() { if (memo.pageUrl) window.location.href = memo.pageUrl; });' +
          'list.appendChild(item);' +
        '})(filtered[i]);' +
      '}' +
    '}' +
    // Filter buttons
    'var filterBtns = document.querySelectorAll(".memo-page-filter-btn");' +
    'filterBtns.forEach(function(btn) {' +
      'btn.addEventListener("click", function() {' +
        'filterBtns.forEach(function(b) { b.classList.remove("active"); });' +
        'btn.classList.add("active");' +
        'currentFilter = btn.getAttribute("data-filter");' +
        'render();' +
      '});' +
    '});' +
    // Export
    'document.getElementById("memoPageExport").addEventListener("click", function() {' +
      'var all = loadAll();' +
      'var blob = new Blob([JSON.stringify(all, null, 2)], {type:"application/json"});' +
      'var url = URL.createObjectURL(blob);' +
      'var a = document.createElement("a"); a.href = url; a.download = "memos.json"; a.click();' +
      'URL.revokeObjectURL(url);' +
    '});' +
    // Import
    'document.getElementById("memoPageImport").addEventListener("click", function() { document.getElementById("memoPageFileInput").click(); });' +
    'document.getElementById("memoPageFileInput").addEventListener("change", function(e) {' +
      'var file = e.target.files && e.target.files[0];' +
      'if (!file) return;' +
      'var reader = new FileReader();' +
      'reader.onload = function() {' +
        'try {' +
          'var imported = JSON.parse(reader.result);' +
          'if (!Array.isArray(imported)) return;' +
          'var existing = loadAll();' +
          'var ids = {};' +
          'for (var i = 0; i < existing.length; i++) ids[existing[i].id] = true;' +
          'var added = imported.filter(function(m) { return m.id && !ids[m.id]; });' +
          'if (added.length > 0) { saveAll(existing.concat(added)); render(); }' +
        '} catch(err) {}' +
      '};' +
      'reader.readAsText(file);' +
      'e.target.value = "";' +
    '});' +
    // Copy
    'document.getElementById("memoPageCopy").addEventListener("click", function() {' +
      'var all = loadAll();' +
      'var text = JSON.stringify(all, null, 2);' +
      'navigator.clipboard.writeText(text).then(function() {' +
        'var btn = document.getElementById("memoPageCopy");' +
        'var orig = btn.innerHTML;' +
        'btn.textContent = copiedMsg;' +
        'setTimeout(function() { btn.innerHTML = orig; }, 1500);' +
      '}).catch(function() {});' +
    '});' +
    // Delete All
    'document.getElementById("memoPageDeleteAll").addEventListener("click", function() {' +
      'if (confirm(confirmMsg)) { saveAll([]); render(); }' +
    '});' +
    'render();' +
  '})();' +
  '</script>';
}

function rewriteInternalLinks(html: string, knownSlugs: Set<string>): string {
  // Rewrite internal .md links to .html (skip external URLs)
  let result = html.replace(/href="([^"]*?)\.md(#[^"]*)?"/g, (match, path, hash) => {
    if (/^(https?:)?\/\//.test(path)) return match;
    return `href="${path}.html${hash || ''}"`;
  });
  // Rewrite directory links (./api/, ./entities/) to directory index.html
  result = result.replace(/href="(\.\/)([a-zA-Z0-9_-]+)\/"/g, (_match, prefix, dir) => {
    if (knownSlugs.has(`${dir}/index`)) {
      return `href="${prefix}${dir}/index.html"`;
    }
    // Fallback: link to first page in that directory
    for (const slug of knownSlugs) {
      if (slug.startsWith(`${dir}/`)) {
        return `href="${prefix}${slug}.html"`;
      }
    }
    return `href="${prefix}${dir}/index.html"`;
  });
  return result;
}

function generateHtmlPage(opts: {
  title: string;
  projectName: string;
  content: string;
  navItems: NavItem[];
  tocHeadings: TocHeading[];
  currentSlug: string;
  pageId: string;
  locale: string;
  s: any;
  basePrefix: string;
  sidebarStructure: any[];
}): string {
  const navHtml = buildNavHtml(opts.navItems);
  const isIndex = opts.currentSlug === 'index';
  const isMemo = opts.currentSlug === 'memo';
  const isSpecialPage = isIndex || isMemo;
  const tocHtml = isSpecialPage ? '' : buildTocHtml(opts.tocHeadings, opts.s);
  const leftSidebarHtml = isSpecialPage ? '' : buildLeftSidebar(opts.sidebarStructure, opts.currentSlug, opts.basePrefix, opts.s);
  const breadcrumbHtml = isSpecialPage ? '' : buildBreadcrumb(opts.sidebarStructure, opts.currentSlug, opts.basePrefix, opts.s);

  let mainContent: string;
  if (isIndex) {
    mainContent = buildDashboardContent(opts.sidebarStructure, opts.basePrefix, opts.projectName, opts.s);
  } else if (isMemo) {
    mainContent = buildMemoPageContent(opts.s);
  } else {
    mainContent = breadcrumbHtml + '\n      <article>\n        ' + opts.content + '\n      </article>';
  }

  const hasLeftSidebar = leftSidebarHtml.length > 0;
  const hasToc = tocHtml.length > 0;
  let layoutClass = 'layout';
  if (isSpecialPage) layoutClass += ' layout-full';
  else if (!hasLeftSidebar && !hasToc) layoutClass += ' layout-single';
  else if (!hasLeftSidebar) layoutClass += ' layout-no-left';
  else if (!hasToc) layoutClass += ' layout-no-toc';

  return `<!DOCTYPE html>
<html lang="${opts.locale}" data-theme="light">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(opts.title)} - ${escapeHtml(opts.projectName)}</title>
  <link rel="stylesheet" href="${opts.basePrefix}assets/style.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/styles/github.min.css" media="(prefers-color-scheme: light), (prefers-color-scheme: no-preference)">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/styles/github-dark.min.css" media="(prefers-color-scheme: dark)">
  <script type="module">
    import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
    mermaid.initialize({ startOnLoad: true, theme: 'default' });
  </script>
</head>
<body>
  <header class="header">
    <div class="header-inner">
      <a href="${opts.basePrefix}index.html" class="logo">${escapeHtml(opts.projectName)}</a>
      <button class="mobile-menu-toggle" id="mobileMenuToggle" aria-label="Toggle menu">
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="18" x2="21" y2="18"/>
        </svg>
      </button>
      <nav class="top-nav" id="topNav">
        <ul class="top-nav-list">
          ${navHtml}
        </ul>
      </nav>
      <div class="header-actions">
        <button class="theme-toggle" onclick="toggleTheme()" aria-label="Toggle theme">
          <svg class="sun-icon" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="5"/><path d="M12 1v2M12 21v2M4.22 4.22l1.42 1.42M18.36 18.36l1.42 1.42M1 12h2M21 12h2M4.22 19.78l1.42-1.42M18.36 5.64l1.42-1.42"/></svg>
          <svg class="moon-icon" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/></svg>
        </button>
      </div>
    </div>
  </header>
  <div class="${layoutClass}">
    ${leftSidebarHtml}
    <main class="content">
      ${mainContent}
      <footer class="footer">
        <p>Generated by <a href="https://github.com/jay05410/codedocs">CodeDocs</a></p>
      </footer>
    </main>
    ${tocHtml}
  </div>

  <!-- Memo: sticky notes container -->
  <div id="memoStickyContainer"></div>

  <!-- Memo: right-click context menu -->
  <div class="codedocs-context-menu" id="memoContextMenu" style="display:none">
    <div class="codedocs-context-menu-item" id="memoContextAdd">${escapeHtml(opts.s.memo.contextAddMemo)}</div>
  </div>

  <!-- Memo: bottom-right controls -->
  <div class="codedocs-memo-controls">
    <button class="codedocs-memo-visibility-btn" id="memoVisibilityBtn" aria-label="${escapeHtml(opts.s.memo.toggleVisibility)}" title="${escapeHtml(opts.s.memo.toggleVisibility)}">
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg>
    </button>
    <button class="codedocs-memo-button" id="memoToggleBtn" aria-label="${escapeHtml(opts.s.memo.title)}">
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-5 14H7v-2h7v2zm3-4H7v-2h10v2zm0-4H7V7h10v2z" fill="currentColor"/>
      </svg>
      <span class="codedocs-memo-badge" id="memoBadge" style="display:none">0</span>
    </button>
  </div>

  <!-- Memo: manager panel -->
  <div class="codedocs-memo-panel" id="memoPanel" style="display:none">
    <div class="codedocs-memo-panel-header">
      <h3>${escapeHtml(opts.s.memo.title)}</h3>
      <div class="codedocs-memo-panel-actions">
        <button class="codedocs-memo-icon-btn" id="memoPanelCopy" title="${escapeHtml(opts.s.memoPage?.copyJson || 'Copy JSON')}">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>
        </button>
        <button class="codedocs-memo-icon-btn" id="memoExportBtn" title="${escapeHtml(opts.s.memo.exportAll)}">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
        </button>
        <input type="file" id="memoFileInput" accept=".json" style="display:none" aria-label="${escapeHtml(opts.s.memo.importFile)}">
      </div>
      <button class="codedocs-memo-close" id="memoCloseBtn" aria-label="Close">&times;</button>
    </div>
    <div class="codedocs-memo-panel-filters">
      <button class="codedocs-memo-toggle-btn active" id="memoFilterToggle">${escapeHtml(opts.s.memo.currentPageOnly || 'Current Page Only')}</button>
    </div>
    <div class="codedocs-memo-list" id="memoList"></div>
  </div>

  <script>
    // Theme toggle
    function toggleTheme() {
      var html = document.documentElement;
      var current = html.getAttribute('data-theme');
      var next = current === 'dark' ? 'light' : 'dark';
      html.setAttribute('data-theme', next);
      localStorage.setItem('codedocs-theme', next);
    }
    (function() {
      var saved = localStorage.getItem('codedocs-theme');
      if (saved) document.documentElement.setAttribute('data-theme', saved);
      else if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
        document.documentElement.setAttribute('data-theme', 'dark');
      }
    })();

    // Mobile menu toggle
    document.getElementById('mobileMenuToggle').addEventListener('click', function() {
      document.getElementById('topNav').classList.toggle('open');
    });

    // TOC scroll spy
    (function() {
      var tocLinks = document.querySelectorAll('.toc-item a');
      var headings = [];
      tocLinks.forEach(function(link) {
        var id = link.getAttribute('href');
        if (!id) return;
        var el = document.getElementById(id.slice(1));
        if (el) headings.push({ el: el, link: link });
      });
      if (headings.length === 0) return;
      function onScroll() {
        var scrollTop = window.scrollY + 100;
        var active = null;
        for (var i = headings.length - 1; i >= 0; i--) {
          if (headings[i].el.offsetTop <= scrollTop) {
            active = headings[i];
            break;
          }
        }
        tocLinks.forEach(function(l) { l.parentElement.classList.remove('active'); });
        if (active) active.link.parentElement.classList.add('active');
      }
      window.addEventListener('scroll', onScroll, { passive: true });
      onScroll();
    })();
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/highlight.min.js"></script>
  <script>
    hljs.highlightAll();
    var observer = new MutationObserver(function() {
      document.querySelectorAll('link[href*="highlight"]').forEach(function(link) {
        if (link.media.includes('light')) {
          link.media = document.documentElement.dataset.theme === 'dark' ? 'not all' : 'all';
        } else {
          link.media = document.documentElement.dataset.theme === 'dark' ? 'all' : 'not all';
        }
      });
    });
    observer.observe(document.documentElement, { attributes: true, attributeFilter: ['data-theme'] });

    // Mermaid copy buttons
    document.querySelectorAll('.mermaid-copy-btn').forEach(function(btn) {
      btn.addEventListener('click', function(e) {
        e.stopPropagation();
        var src = atob(btn.dataset.source);
        navigator.clipboard.writeText(src).then(function() {
          var orig = btn.innerHTML;
          btn.innerHTML = '<span class="mermaid-copied">Copied!</span>';
          btn.classList.add('copied');
          setTimeout(function() { btn.innerHTML = orig; btn.classList.remove('copied'); }, 1500);
        }).catch(function() {});
      });
    });

    // Mermaid expand buttons
    document.querySelectorAll('.mermaid-expand-btn').forEach(function(btn) {
      btn.addEventListener('click', function(e) {
        e.stopPropagation();
        var wrapper = btn.closest('.mermaid-wrapper');
        var svgEl = wrapper.querySelector('.mermaid svg');
        if (!svgEl) return;
        var svgMarkup = svgEl.outerHTML;
        var overlay = document.createElement('div');
        overlay.className = 'mermaid-overlay';
        var BASE_SCALE = 5;
        var zoom = 100;
        overlay.innerHTML =
          '<div class="mermaid-popup">' +
            '<div class="mermaid-popup-header">' +
              '<div class="mermaid-zoom-controls">' +
                '<button class="mermaid-zoom-btn" data-action="out">-</button>' +
                '<span class="mermaid-zoom-level">' + zoom + '%</span>' +
                '<button class="mermaid-zoom-btn" data-action="in">+</button>' +
              '</div>' +
              '<button class="mermaid-close-btn" title="Close">' +
                '<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M18 6L6 18M6 6l12 12"/></svg>' +
              '</button>' +
            '</div>' +
            '<div class="mermaid-popup-body">' +
              '<div class="mermaid-popup-content" style="transform:scale(' + BASE_SCALE + ')">' + svgMarkup + '</div>' +
            '</div>' +
          '</div>';
        document.body.appendChild(overlay);
        requestAnimationFrame(function() { overlay.classList.add('active'); });
        var content = overlay.querySelector('.mermaid-popup-content');
        var levelEl = overlay.querySelector('.mermaid-zoom-level');
        var popupSvg = content.querySelector('svg');
        if (popupSvg) { popupSvg.style.maxWidth = 'none'; popupSvg.style.maxHeight = 'none'; }
        overlay.querySelector('[data-action="in"]').addEventListener('click', function() {
          zoom = Math.min(zoom + 10, 500);
          content.style.transform = 'scale(' + (BASE_SCALE * zoom / 100) + ')';
          levelEl.textContent = zoom + '%';
        });
        overlay.querySelector('[data-action="out"]').addEventListener('click', function() {
          zoom = Math.max(zoom - 10, 10);
          content.style.transform = 'scale(' + (BASE_SCALE * zoom / 100) + ')';
          levelEl.textContent = zoom + '%';
        });
        var closePopup = function() {
          overlay.classList.remove('active');
          setTimeout(function() { overlay.remove(); }, 200);
        };
        overlay.querySelector('.mermaid-close-btn').addEventListener('click', closePopup);
        overlay.addEventListener('click', function(ev) { if (ev.target === overlay) closePopup(); });
        document.addEventListener('keydown', function esc(ev) {
          if (ev.key === 'Escape') { closePopup(); document.removeEventListener('keydown', esc); }
        });
      });
    });
  </script>
  <script>
    // Memo System - Sticky Notes (i18n)
    (function() {
      var PAGE_ID = ${JSON.stringify(opts.pageId)};
      var PAGE_URL = ${JSON.stringify(opts.currentSlug + '.html')};
      var PAGE_TITLE = ${JSON.stringify(opts.title)};
      var STORAGE_KEY = 'codedocs-memos';
      var STRINGS = ${JSON.stringify(opts.s.memo)};
      var COLORS = ['#fff9c4','#c8e6c9','#bbdefb','#f8bbd0','#ffe0b2','#e1bee7','#b2dfdb'];
      var CATEGORIES = {important:'!',add:'+',modify:'~','delete':'-',other:'?'};
      var CAT_NAMES = {important:STRINGS.important,add:STRINGS.add,modify:STRINGS.modify,'delete':STRINGS['delete'],other:STRINGS.other};
      var memosVisible = true;

      var stickyContainer = document.getElementById('memoStickyContainer');
      var toggleBtn = document.getElementById('memoToggleBtn');
      var badge = document.getElementById('memoBadge');
      var visibilityBtn = document.getElementById('memoVisibilityBtn');
      var panel = document.getElementById('memoPanel');
      var closeBtn = document.getElementById('memoCloseBtn');
      var memoList = document.getElementById('memoList');
      var exportBtn = document.getElementById('memoExportBtn');
      var fileInput = document.getElementById('memoFileInput');
      var contextMenu = document.getElementById('memoContextMenu');
      var contextAdd = document.getElementById('memoContextAdd');
      var filterToggle = document.getElementById('memoFilterToggle');
      var panelCopyBtn = document.getElementById('memoPanelCopy');
      var currentPageOnly = true;
      var contextX = 0;
      var contextY = 0;

      function loadAllMemos() {
        try {
          var stored = localStorage.getItem(STORAGE_KEY);
          if (!stored) return [];
          var parsed = JSON.parse(stored);
          return Array.isArray(parsed) ? parsed : [];
        } catch(e) { return []; }
      }
      function saveAllMemos(memos) {
        try { localStorage.setItem(STORAGE_KEY, JSON.stringify(memos)); } catch(e) {
          if (e.name === 'QuotaExceededError') { alert(STRINGS.exportAll + ' - Storage full'); }
        }
      }
      function getPageMemos() {
        return loadAllMemos().filter(function(m) { return m.docId === PAGE_ID; });
      }
      function formatTimestamp(iso) {
        var d = new Date(iso);
        return d.toLocaleString(undefined, { year:'numeric', month:'short', day:'numeric', hour:'2-digit', minute:'2-digit' });
      }
      function updateBadge() {
        var count = getPageMemos().length;
        if (count > 0) { badge.textContent = count; badge.style.display = 'flex'; }
        else { badge.style.display = 'none'; }
      }
      function getCatIcon(cat) { return CATEGORIES[cat] || '?'; }

      // --- Sticky Note DOM ---
      function createStickyEl(memo) {
        var note = document.createElement('div');
        note.className = 'codedocs-sticky' + (memo.minimized ? ' minimized' : '');
        note.setAttribute('data-memo-id', memo.id);
        note.style.left = memo.x + 'px';
        note.style.top = memo.y + 'px';
        note.style.width = (memo.width || 280) + 'px';
        note.style.backgroundColor = memo.color || COLORS[0];
        if (!memo.minimized) {
          note.style.height = (memo.height || 200) + 'px';
        }

        // Header
        var header = document.createElement('div');
        header.className = 'codedocs-sticky-header';
        header.style.backgroundColor = memo.color || COLORS[0];

        var catSelect = document.createElement('select');
        catSelect.className = 'codedocs-sticky-cat-select';
        var catKeys = Object.keys(CATEGORIES);
        for (var ci = 0; ci < catKeys.length; ci++) {
          var opt = document.createElement('option');
          opt.value = catKeys[ci];
          opt.textContent = CATEGORIES[catKeys[ci]] + ' ' + (CAT_NAMES[catKeys[ci]] || catKeys[ci]);
          if (catKeys[ci] === memo.category) opt.selected = true;
          catSelect.appendChild(opt);
        }
        catSelect.addEventListener('change', function() {
          updateMemoField(memo.id, 'category', catSelect.value);
        });
        header.appendChild(catSelect);

        var headerBtns = document.createElement('div');
        headerBtns.className = 'codedocs-sticky-header-btns';

        var minBtn = document.createElement('button');
        minBtn.className = 'codedocs-sticky-btn';
        minBtn.innerHTML = '&#8211;';
        minBtn.title = STRINGS.minimize;
        minBtn.addEventListener('click', function(ev) {
          ev.stopPropagation();
          toggleMinimize(memo.id);
        });

        var closeNoteBtn = document.createElement('button');
        closeNoteBtn.className = 'codedocs-sticky-btn';
        closeNoteBtn.innerHTML = '&times;';
        closeNoteBtn.title = STRINGS.deleteMemo;
        closeNoteBtn.addEventListener('click', function(ev) {
          ev.stopPropagation();
          deleteMemo(memo.id);
        });

        headerBtns.appendChild(minBtn);
        headerBtns.appendChild(closeNoteBtn);
        header.appendChild(headerBtns);
        note.appendChild(header);

        if (memo.minimized) {
          // Minimized: show just category icon tag
          var minTag = document.createElement('div');
          minTag.className = 'codedocs-sticky-min-tag';
          minTag.textContent = getCatIcon(memo.category);
          minTag.addEventListener('click', function() { toggleMinimize(memo.id); });
          note.innerHTML = '';
          note.appendChild(minTag);
          return note;
        }

        // Target field
        var targetInput = document.createElement('input');
        targetInput.className = 'codedocs-sticky-target';
        targetInput.type = 'text';
        targetInput.placeholder = STRINGS.target;
        targetInput.value = memo.target || '';
        targetInput.addEventListener('change', function() {
          updateMemoField(memo.id, 'target', targetInput.value);
        });
        targetInput.addEventListener('keydown', function(ev) {
          if ((ev.ctrlKey || ev.metaKey) && ev.key === 'Enter') { commitNote(memo.id); }
        });
        note.appendChild(targetInput);

        // Content textarea
        var contentArea = document.createElement('textarea');
        contentArea.className = 'codedocs-sticky-content';
        contentArea.placeholder = STRINGS.placeholder;
        contentArea.value = memo.content || '';
        contentArea.title = STRINGS.finishEditing;
        contentArea.addEventListener('change', function() {
          updateMemoField(memo.id, 'content', contentArea.value);
        });
        contentArea.addEventListener('keydown', function(ev) {
          if ((ev.ctrlKey || ev.metaKey) && ev.key === 'Enter') { commitNote(memo.id); }
        });
        note.appendChild(contentArea);

        // Color bar
        var colorBar = document.createElement('div');
        colorBar.className = 'codedocs-sticky-colors';
        for (var i = 0; i < COLORS.length; i++) {
          (function(c) {
            var circle = document.createElement('span');
            circle.className = 'codedocs-sticky-color-circle' + (c === (memo.color || COLORS[0]) ? ' active' : '');
            circle.style.backgroundColor = c;
            circle.addEventListener('click', function() {
              updateMemoField(memo.id, 'color', c);
              renderStickies();
            });
            colorBar.appendChild(circle);
          })(COLORS[i]);
        }
        note.appendChild(colorBar);

        // Drag
        makeDraggable(note, header, memo.id);
        // Resize
        makeResizable(note, memo.id);

        return note;
      }

      function makeDraggable(el, handle, memoId) {
        var startX, startY, origX, origY;
        handle.addEventListener('mousedown', function(ev) {
          if (ev.target.tagName === 'SELECT' || ev.target.tagName === 'BUTTON') return;
          ev.preventDefault();
          startX = ev.clientX;
          startY = ev.clientY;
          origX = parseInt(el.style.left, 10) || 0;
          origY = parseInt(el.style.top, 10) || 0;
          function onMove(e) {
            var dx = e.clientX - startX;
            var dy = e.clientY - startY;
            el.style.left = (origX + dx) + 'px';
            el.style.top = (origY + dy) + 'px';
          }
          function onUp() {
            document.removeEventListener('mousemove', onMove);
            document.removeEventListener('mouseup', onUp);
            updateMemoField(memoId, 'x', parseInt(el.style.left, 10));
            updateMemoField(memoId, 'y', parseInt(el.style.top, 10));
          }
          document.addEventListener('mousemove', onMove);
          document.addEventListener('mouseup', onUp);
        });
      }

      function makeResizable(el, memoId) {
        var resizeHandle = document.createElement('div');
        resizeHandle.className = 'codedocs-sticky-resize';
        el.appendChild(resizeHandle);
        var startX, startY, startW, startH;
        resizeHandle.addEventListener('mousedown', function(ev) {
          ev.preventDefault();
          ev.stopPropagation();
          startX = ev.clientX;
          startY = ev.clientY;
          startW = el.offsetWidth;
          startH = el.offsetHeight;
          function onMove(e) {
            var nw = startW + (e.clientX - startX);
            var nh = startH + (e.clientY - startY);
            if (nw > 180) el.style.width = nw + 'px';
            if (nh > 120) el.style.height = nh + 'px';
          }
          function onUp() {
            document.removeEventListener('mousemove', onMove);
            document.removeEventListener('mouseup', onUp);
            updateMemoField(memoId, 'width', el.offsetWidth);
            updateMemoField(memoId, 'height', el.offsetHeight);
          }
          document.addEventListener('mousemove', onMove);
          document.addEventListener('mouseup', onUp);
        });
      }

      // --- Data operations ---
      function createMemo(x, y, target) {
        var memo = {
          id: 'memo-' + Date.now() + '-' + Math.random().toString(36).slice(2, 11),
          docId: PAGE_ID,
          pageUrl: PAGE_URL,
          pageTitle: PAGE_TITLE,
          content: '',
          category: 'other',
          target: target || '',
          createdAt: new Date().toISOString(),
          x: x,
          y: y,
          color: COLORS[0],
          minimized: false,
          width: 280,
          height: 200
        };
        var all = loadAllMemos();
        all.push(memo);
        saveAllMemos(all);
        renderStickies();
        updateBadge();
        renderPanelList();
        return memo;
      }

      function updateMemoField(id, field, value) {
        var all = loadAllMemos();
        for (var i = 0; i < all.length; i++) {
          if (all[i].id === id) { all[i][field] = value; break; }
        }
        saveAllMemos(all);
        updateBadge();
      }

      function toggleMinimize(id) {
        var all = loadAllMemos();
        for (var i = 0; i < all.length; i++) {
          if (all[i].id === id) { all[i].minimized = !all[i].minimized; break; }
        }
        saveAllMemos(all);
        renderStickies();
      }

      function commitNote(id) {
        // Blur active element to save, then re-render
        if (document.activeElement) document.activeElement.blur();
        renderStickies();
      }

      function deleteMemo(id) {
        var all = loadAllMemos().filter(function(m) { return m.id !== id; });
        saveAllMemos(all);
        renderStickies();
        updateBadge();
        renderPanelList();
      }

      // --- Render sticky notes on page ---
      function renderStickies() {
        stickyContainer.innerHTML = '';
        if (!memosVisible) return;
        var pageMemos = getPageMemos();
        for (var i = 0; i < pageMemos.length; i++) {
          stickyContainer.appendChild(createStickyEl(pageMemos[i]));
        }
      }

      // --- Panel list ---
      function renderPanelList() {
        var memos;
        if (currentPageOnly) {
          memos = getPageMemos();
        } else {
          memos = loadAllMemos();
        }
        memos.sort(function(a, b) { return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime(); });
        memoList.innerHTML = '';
        if (memos.length === 0) {
          memoList.innerHTML = '<div class="codedocs-memo-empty">' + STRINGS.noMemos + '</div>';
          return;
        }
        for (var i = 0; i < memos.length; i++) {
          (function(memo) {
            var item = document.createElement('div');
            item.className = 'codedocs-memo-item';
            item.style.borderLeft = '4px solid ' + (memo.color || COLORS[0]);

            var catSpan = document.createElement('span');
            catSpan.className = 'codedocs-memo-cat-icon';
            catSpan.textContent = getCatIcon(memo.category);

            var info = document.createElement('div');
            info.className = 'codedocs-memo-item-info';

            var targetEl = document.createElement('div');
            targetEl.className = 'codedocs-memo-item-target';
            targetEl.textContent = memo.target || '(' + STRINGS.target + ')';

            var contentEl = document.createElement('div');
            contentEl.className = 'codedocs-memo-item-content';
            var truncated = (memo.content || '').length > 60 ? (memo.content || '').slice(0, 60) + '...' : (memo.content || STRINGS.noMemos);
            contentEl.textContent = truncated;

            var metaEl = document.createElement('div');
            metaEl.className = 'codedocs-memo-item-meta';
            metaEl.textContent = (memo.pageTitle || '') + ' - ' + formatTimestamp(memo.createdAt);

            info.appendChild(targetEl);
            info.appendChild(contentEl);
            info.appendChild(metaEl);

            item.appendChild(catSpan);
            item.appendChild(info);

            item.addEventListener('click', function() {
              if (memo.docId !== PAGE_ID) {
                // Navigate to the page
                window.location.href = memo.pageUrl;
                return;
              }
              // Scroll to memo position
              window.scrollTo({ top: Math.max(0, memo.y - 100), behavior: 'smooth' });
              // Ensure visible
              if (!memosVisible) {
                memosVisible = true;
                renderStickies();
              }
            });

            memoList.appendChild(item);
          })(memos[i]);
        }
      }

      // --- Export / Import ---
      function exportAllMemos() {
        var all = loadAllMemos();
        var blob = new Blob([JSON.stringify(all, null, 2)], { type: 'application/json' });
        var url = URL.createObjectURL(blob);
        var a = document.createElement('a'); a.href = url; a.download = 'memos.json'; a.click();
        URL.revokeObjectURL(url);
      }
      function importMemos(file) {
        var reader = new FileReader();
        reader.onload = function() {
          try {
            var imported = JSON.parse(reader.result);
            if (!Array.isArray(imported)) return;
            var existing = loadAllMemos();
            var existingIds = {};
            for (var i = 0; i < existing.length; i++) { existingIds[existing[i].id] = true; }
            var added = imported.filter(function(m) { return m.id && !existingIds[m.id]; });
            if (added.length > 0) {
              saveAllMemos(existing.concat(added));
              renderStickies();
              updateBadge();
              renderPanelList();
            }
          } catch(e) {}
        };
        reader.readAsText(file);
      }

      // --- Event bindings ---
      toggleBtn.addEventListener('click', function() {
        var isOpen = panel.style.display !== 'none';
        panel.style.display = isOpen ? 'none' : 'flex';
        if (!isOpen) renderPanelList();
      });
      closeBtn.addEventListener('click', function() { panel.style.display = 'none'; });

      visibilityBtn.addEventListener('click', function() {
        memosVisible = !memosVisible;
        visibilityBtn.classList.toggle('off', !memosVisible);
        renderStickies();
      });

      filterToggle.addEventListener('click', function() {
        currentPageOnly = !currentPageOnly;
        filterToggle.classList.toggle('active', currentPageOnly);
        renderPanelList();
      });

      exportBtn.addEventListener('click', exportAllMemos);
      panelCopyBtn.addEventListener('click', function() {
        var all = loadAllMemos();
        var text = JSON.stringify(all, null, 2);
        navigator.clipboard.writeText(text).then(function() {
          var orig = panelCopyBtn.innerHTML;
          panelCopyBtn.innerHTML = '<span style="font-size:0.7rem">' + (STRINGS.copied || 'Copied!') + '</span>';
          setTimeout(function() { panelCopyBtn.innerHTML = orig; }, 1500);
        }).catch(function() {});
      });
      fileInput.addEventListener('change', function(e) {
        var file = e.target.files && e.target.files[0];
        if (file) importMemos(file);
        e.target.value = '';
      });

      // Context menu on article area
      var article = document.querySelector('article');
      if (article) {
        article.addEventListener('contextmenu', function(e) {
          e.preventDefault();
          contextX = e.pageX;
          contextY = e.pageY;
          contextMenu.style.display = 'block';
          contextMenu.style.left = e.pageX + 'px';
          contextMenu.style.top = e.pageY + 'px';
        });
      }
      contextAdd.addEventListener('click', function() {
        contextMenu.style.display = 'none';
        var sel = (window.getSelection() || '').toString().trim();
        var memo = createMemo(contextX, contextY, sel);
      });
      document.addEventListener('click', function(e) {
        if (!contextMenu.contains(e.target)) contextMenu.style.display = 'none';
      });
      document.addEventListener('keydown', function(e) {
        if (e.key === 'Escape') {
          contextMenu.style.display = 'none';
          if (panel.style.display !== 'none') panel.style.display = 'none';
        }
      });

      // Init
      updateBadge();
      renderStickies();
    })();
  </script>
</body>
</html>`;
}

function getStylesheet(): string {
  return `
:root, [data-theme="light"] {
  --bg: #ffffff;
  --bg-secondary: #f6f8fa;
  --bg-tertiary: #eef1f5;
  --text: #1a1a2e;
  --text-secondary: #57606a;
  --text-muted: #8b949e;
  --border: #d1d9e0;
  --border-light: #e8ecf0;
  --primary: #0969da;
  --primary-hover: #0550ae;
  --primary-light: #ddf4ff;
  --primary-subtle: #f0f7ff;
  --code-bg: #f6f8fa;
  --header-bg: #ffffff;
  --shadow: 0 1px 2px rgba(31,35,40,0.04), 0 1px 3px rgba(31,35,40,0.08);
  --shadow-md: 0 3px 6px rgba(31,35,40,0.08), 0 2px 4px rgba(31,35,40,0.06);
  --radius: 8px;
  --radius-lg: 12px;
}
[data-theme="dark"] {
  --bg: #0d1117;
  --bg-secondary: #161b22;
  --bg-tertiary: #1c2129;
  --text: #e6edf3;
  --text-secondary: #8b949e;
  --text-muted: #6e7681;
  --border: #30363d;
  --border-light: #21262d;
  --primary: #58a6ff;
  --primary-hover: #79c0ff;
  --primary-light: #0d2746;
  --primary-subtle: #0d1d31;
  --code-bg: #161b22;
  --header-bg: #161b22;
  --shadow: 0 1px 3px rgba(0,0,0,0.2);
  --shadow-md: 0 3px 6px rgba(0,0,0,0.3);
  --radius: 8px;
  --radius-lg: 12px;
}
* { margin: 0; padding: 0; box-sizing: border-box; }
html { scroll-behavior: smooth; }
body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif;
  color: var(--text);
  background: var(--bg);
  line-height: 1.7;
  font-size: 16px;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

/* ── Header ── */
.header {
  position: sticky;
  top: 0;
  z-index: 100;
  background: var(--header-bg);
  border-bottom: 1px solid var(--border);
  box-shadow: var(--shadow);
  backdrop-filter: blur(8px);
}
.header-inner {
  max-width: 1400px;
  margin: 0 auto;
  padding: 0 1.5rem;
  height: 56px;
  display: flex;
  align-items: center;
  gap: 1.5rem;
}
.logo {
  font-size: 1.2rem;
  font-weight: 700;
  color: var(--text);
  text-decoration: none;
  letter-spacing: -0.02em;
  white-space: nowrap;
  flex-shrink: 0;
}
.logo:hover { color: var(--primary); }
.header-actions {
  margin-left: auto;
  flex-shrink: 0;
}
.theme-toggle {
  background: var(--bg-secondary);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 6px 8px;
  cursor: pointer;
  color: var(--text-secondary);
  display: flex;
  align-items: center;
  transition: all 0.15s;
}
.theme-toggle:hover { color: var(--text); border-color: var(--text-muted); }
[data-theme="light"] .moon-icon { display: none; }
[data-theme="dark"] .sun-icon { display: none; }

/* ── Top Navigation ── */
.top-nav {
  flex: 1;
  min-width: 0;
}
.top-nav-list {
  list-style: none;
  display: flex;
  align-items: center;
  gap: 2px;
  flex-wrap: nowrap;
  overflow-x: auto;
  scrollbar-width: none;
}
.top-nav-list::-webkit-scrollbar { display: none; }
.top-nav-item {
  position: relative;
  flex-shrink: 0;
}
.top-nav-link {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  padding: 6px 12px;
  font-size: 0.875rem;
  font-weight: 500;
  color: var(--text-secondary);
  text-decoration: none;
  border-radius: 6px;
  border: none;
  background: none;
  cursor: pointer;
  white-space: nowrap;
  transition: color 0.12s, background 0.12s;
  font-family: inherit;
}
.top-nav-link:hover {
  color: var(--text);
  background: var(--bg-tertiary);
}
.top-nav-link.active {
  color: var(--primary);
  font-weight: 600;
}

/* ── Mobile hamburger ── */
.mobile-menu-toggle {
  display: none;
  background: none;
  border: 1px solid var(--border);
  border-radius: 6px;
  padding: 4px 6px;
  cursor: pointer;
  color: var(--text-secondary);
  flex-shrink: 0;
}
.mobile-menu-toggle:hover { color: var(--text); border-color: var(--text-muted); }

/* ── Layout (3-column grid) ── */
.layout {
  display: grid;
  grid-template-columns: 250px 1fr 220px;
  max-width: 1400px;
  margin: 0 auto;
  min-height: calc(100vh - 56px);
}
.layout-full {
  grid-template-columns: 1fr;
}
.layout-single {
  grid-template-columns: 1fr;
}
.layout-no-left {
  grid-template-columns: 1fr 220px;
}
.layout-no-toc {
  grid-template-columns: 250px 1fr;
}
.content {
  padding: 2rem 3rem;
  min-width: 0;
}

/* ── Left Sidebar ── */
.left-sidebar {
  width: 250px;
  padding: 1.5rem 1rem;
  position: sticky;
  top: 56px;
  height: calc(100vh - 56px);
  overflow-y: auto;
  border-right: 1px solid var(--border-light);
  scrollbar-width: thin;
  scrollbar-color: var(--border) transparent;
}
.left-sidebar::-webkit-scrollbar { width: 4px; }
.left-sidebar::-webkit-scrollbar-track { background: transparent; }
.left-sidebar::-webkit-scrollbar-thumb { background: var(--border); border-radius: 4px; }
.left-sidebar-title {
  font-size: 0.75rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: var(--text-muted);
  margin-bottom: 0.75rem;
  padding: 0 0.5rem;
}
.left-sidebar-list {
  list-style: none;
  padding: 0;
  margin: 0;
}
.left-sidebar-item a {
  display: block;
  padding: 6px 12px;
  font-size: 0.85rem;
  color: var(--text-secondary);
  text-decoration: none;
  border-radius: 6px;
  transition: color 0.12s, background 0.12s;
}
.left-sidebar-item a:hover {
  color: var(--text);
  background: var(--bg-tertiary);
}
.left-sidebar-item.active a {
  color: var(--primary);
  font-weight: 600;
  background: var(--primary-subtle);
}

/* ── Breadcrumb ── */
.breadcrumb {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 0.75rem 0;
  margin-bottom: 0.5rem;
  font-size: 0.8rem;
  color: var(--text-muted);
}
.breadcrumb-item { color: var(--text-secondary); text-decoration: none; }
.breadcrumb-item:hover { color: var(--primary); }
.breadcrumb-home { display: flex; align-items: center; }
.breadcrumb-current { color: var(--text); font-weight: 500; }
.breadcrumb-sep { color: var(--text-muted); font-size: 0.75rem; }

/* ── TOC Sidebar ── */
.toc-sidebar {
  width: 220px;
  min-width: 220px;
  padding: 2rem 1rem 2rem 0;
  position: sticky;
  top: 56px;
  height: calc(100vh - 56px);
  overflow-y: auto;
  scrollbar-width: thin;
  scrollbar-color: var(--border) transparent;
  flex-shrink: 0;
}
.toc-sidebar::-webkit-scrollbar { width: 4px; }
.toc-sidebar::-webkit-scrollbar-track { background: transparent; }
.toc-sidebar::-webkit-scrollbar-thumb { background: var(--border); border-radius: 4px; }
.toc-container {
  border-left: 1px solid var(--border-light);
  padding-left: 1rem;
}
.toc-title {
  font-size: 0.75rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: var(--text-muted);
  margin-bottom: 0.75rem;
}
.toc-list {
  list-style: none;
  padding: 0;
  margin: 0;
}
.toc-item {
  margin: 0;
}
.toc-item a {
  display: block;
  padding: 3px 0;
  font-size: 0.8rem;
  color: var(--text-secondary);
  text-decoration: none;
  line-height: 1.5;
  transition: color 0.12s;
}
.toc-item a:hover { color: var(--text); }
.toc-item.active a {
  color: var(--primary);
  font-weight: 600;
}
.toc-h3 { padding-left: 0.75rem; }

/* ── Dashboard ── */
.dashboard { padding: 3rem 2rem; max-width: 900px; margin: 0 auto; }
.dashboard-header { text-align: center; margin-bottom: 3rem; }
.dashboard-title { font-size: 2.5rem; font-weight: 700; letter-spacing: -0.02em; }
.dashboard-subtitle { color: var(--text-secondary); font-size: 1.1rem; margin-top: 0.5rem; }
.dashboard-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
  gap: 1rem;
}
.dashboard-card {
  display: flex;
  align-items: flex-start;
  gap: 1rem;
  padding: 1.25rem;
  background: var(--bg-secondary);
  border: 1px solid var(--border);
  border-radius: var(--radius-lg);
  text-decoration: none;
  color: var(--text);
  transition: border-color 0.15s, box-shadow 0.15s, transform 0.15s;
}
.dashboard-card:hover {
  border-color: var(--primary);
  box-shadow: var(--shadow-md);
  transform: translateY(-2px);
}
.dashboard-card-icon {
  width: 48px;
  height: 48px;
  border-radius: var(--radius);
  background: var(--primary-subtle);
  color: var(--primary);
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}
.dashboard-card-icon svg { width: 24px; height: 24px; }
.dashboard-card-info h3 {
  font-size: 1rem;
  font-weight: 600;
  margin-bottom: 0.25rem;
}
.dashboard-card-info p {
  font-size: 0.85rem;
  color: var(--text-secondary);
  line-height: 1.5;
  margin: 0;
}

/* ── Memo Page ── */
.memo-page { padding: 2rem; max-width: 900px; margin: 0 auto; }
.memo-page-header { margin-bottom: 1.5rem; }
.memo-page-header h1 { font-size: 1.75rem; font-weight: 700; margin-bottom: 0.5rem; }
.memo-page-desc { color: var(--text-secondary); font-size: 0.9rem; line-height: 1.6; }
.memo-page-actions {
  display: flex;
  gap: 8px;
  margin-bottom: 1rem;
  flex-wrap: wrap;
}
.memo-page-action-btn {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 8px 16px;
  background: var(--bg-secondary);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  color: var(--text-secondary);
  font-size: 0.85rem;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.15s;
}
.memo-page-action-btn:hover {
  background: var(--bg-tertiary);
  border-color: var(--primary);
  color: var(--text);
}
.memo-page-danger-btn:hover {
  border-color: #ef4444;
  color: #ef4444;
}
.memo-page-filters {
  display: flex;
  gap: 6px;
  margin-bottom: 1rem;
  flex-wrap: wrap;
}
.memo-page-filter-btn {
  padding: 6px 14px;
  background: var(--bg);
  border: 1px solid var(--border);
  border-radius: 16px;
  color: var(--text-secondary);
  font-size: 0.8rem;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.15s;
}
.memo-page-filter-btn:hover { border-color: var(--primary); color: var(--text); }
.memo-page-filter-btn.active {
  background: var(--primary-subtle);
  color: var(--primary);
  border-color: var(--primary);
}
.memo-page-count {
  font-size: 0.8rem;
  color: var(--text-muted);
  margin-bottom: 0.75rem;
}
.memo-page-list {
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.memo-page-empty {
  text-align: center;
  color: var(--text-muted);
  font-size: 0.9rem;
  padding: 3rem 0;
}
.memo-page-item {
  display: flex;
  align-items: flex-start;
  gap: 10px;
  padding: 12px;
  background: var(--bg-secondary);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  cursor: pointer;
  transition: background 0.15s;
}
.memo-page-item:hover { background: var(--bg-tertiary); }
.memo-page-item-cat {
  width: 28px;
  height: 28px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: 700;
  font-size: 0.95rem;
  color: var(--text-secondary);
  flex-shrink: 0;
  background: var(--bg);
  border-radius: 6px;
}
.memo-page-item-info { flex: 1; min-width: 0; }
.memo-page-item-target {
  font-size: 0.85rem;
  font-weight: 600;
  color: var(--text);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.memo-page-item-content {
  font-size: 0.8rem;
  color: var(--text-secondary);
  margin-top: 2px;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
.memo-page-item-meta {
  font-size: 0.7rem;
  color: var(--text-muted);
  margin-top: 4px;
}

/* ── Article ── */
article h1 {
  font-size: 2rem;
  font-weight: 700;
  margin-bottom: 1rem;
  padding-bottom: 0.5rem;
  border-bottom: 1px solid var(--border);
  letter-spacing: -0.02em;
  line-height: 1.3;
}
article h2 {
  font-size: 1.4rem;
  font-weight: 600;
  margin: 2.5rem 0 0.75rem;
  padding-bottom: 0.3rem;
  border-bottom: 1px solid var(--border-light);
  letter-spacing: -0.01em;
  line-height: 1.4;
}
article h3 { font-size: 1.15rem; font-weight: 600; margin: 1.75rem 0 0.5rem; line-height: 1.4; }
article p { margin: 0.75rem 0; line-height: 1.75; }
article ul, article ol { margin: 0.75rem 0; padding-left: 1.75rem; }
article li { margin: 0.35rem 0; line-height: 1.65; }
article li::marker { color: var(--text-muted); }
article a { color: var(--primary); text-decoration: none; font-weight: 500; }
article a:hover { text-decoration: underline; color: var(--primary-hover); }
article table {
  width: 100%;
  border-collapse: collapse;
  margin: 1.25rem 0;
  font-size: 0.875rem;
  border: 1px solid var(--border);
  border-radius: var(--radius);
  overflow: hidden;
}
article th {
  background: var(--bg-secondary);
  font-weight: 600;
  text-align: left;
  padding: 0.65rem 0.85rem;
  border-bottom: 1px solid var(--border);
  font-size: 0.8rem;
  text-transform: uppercase;
  letter-spacing: 0.03em;
  color: var(--text-secondary);
}
article td {
  padding: 0.55rem 0.85rem;
  border-bottom: 1px solid var(--border-light);
}
article tr:last-child td { border-bottom: none; }
article tr:hover { background: var(--bg-secondary); }
article code {
  background: var(--code-bg);
  padding: 0.15rem 0.4rem;
  border-radius: 4px;
  font-size: 0.85em;
  font-family: 'SF Mono', 'Fira Code', 'Cascadia Code', monospace;
  border: 1px solid var(--border-light);
}
article pre {
  background: var(--code-bg);
  padding: 1rem 1.25rem;
  border-radius: var(--radius);
  overflow-x: auto;
  margin: 1.25rem 0;
  border: 1px solid var(--border);
}
article pre code {
  background: none;
  padding: 0;
  font-size: 0.85rem;
  line-height: 1.65;
  border: none;
}
article blockquote {
  border-left: 3px solid var(--primary);
  padding: 0.75rem 1.25rem;
  margin: 1.25rem 0;
  background: var(--primary-subtle);
  border-radius: 0 var(--radius) var(--radius) 0;
  color: var(--text-secondary);
}
article details {
  margin: 1rem 0;
  padding: 0.75rem 1rem;
  background: var(--bg-secondary);
  border-radius: var(--radius);
  border: 1px solid var(--border-light);
}
article summary {
  cursor: pointer;
  font-weight: 500;
  color: var(--text-secondary);
  font-size: 0.9rem;
}
article summary:hover { color: var(--text); }
article hr { border: none; border-top: 1px solid var(--border-light); margin: 2rem 0; }
article strong { font-weight: 600; }

/* ── Mermaid wrapper ── */
.mermaid-wrapper {
  position: relative;
  margin: 1.5rem 0;
  border: 1px solid var(--border);
  border-radius: var(--radius-lg);
  padding: 1.25rem;
  background: var(--bg-secondary);
}
.mermaid-wrapper:hover .mermaid-toolbar { opacity: 1; }
.mermaid { text-align: center; }
.mermaid svg { max-width: 100%; height: auto; }
.mermaid-toolbar {
  position: absolute;
  top: 8px;
  right: 8px;
  display: flex;
  gap: 4px;
  opacity: 0;
  transition: opacity 0.15s ease;
  z-index: 10;
}
.mermaid-copy-btn, .mermaid-expand-btn {
  background: var(--bg);
  border: 1px solid var(--border);
  border-radius: 6px;
  padding: 5px 7px;
  cursor: pointer;
  color: var(--text-secondary);
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.12s ease;
  font-size: 0.75rem;
}
.mermaid-copy-btn:hover, .mermaid-expand-btn:hover {
  background: var(--bg-tertiary);
  color: var(--text);
  border-color: var(--text-muted);
}
.mermaid-copy-btn.copied {
  background: var(--primary-subtle);
  color: var(--primary);
  border-color: var(--primary);
}
.mermaid-copied { font-size: 0.75rem; font-weight: 600; padding: 0 2px; }

/* ── Mermaid popup overlay ── */
.mermaid-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0,0,0,0.6);
  backdrop-filter: blur(4px);
  z-index: 9999;
  display: flex;
  align-items: center;
  justify-content: center;
  opacity: 0;
  transition: opacity 0.2s ease;
}
.mermaid-overlay.active { opacity: 1; }
.mermaid-popup {
  background: var(--bg);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-md);
  width: 90vw;
  height: 85vh;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}
.mermaid-popup-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0.75rem 1rem;
  border-bottom: 1px solid var(--border);
  background: var(--bg-secondary);
  flex-shrink: 0;
}
.mermaid-zoom-controls {
  display: flex;
  align-items: center;
  gap: 8px;
}
.mermaid-zoom-btn {
  background: var(--bg);
  border: 1px solid var(--border);
  border-radius: 6px;
  width: 32px;
  height: 32px;
  cursor: pointer;
  color: var(--text);
  font-size: 1.1rem;
  font-weight: 600;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.12s;
}
.mermaid-zoom-btn:hover { background: var(--bg-tertiary); border-color: var(--text-muted); }
.mermaid-zoom-level {
  font-size: 0.85rem;
  font-weight: 600;
  color: var(--text-secondary);
  min-width: 48px;
  text-align: center;
  font-variant-numeric: tabular-nums;
}
.mermaid-close-btn {
  background: none;
  border: 1px solid var(--border);
  border-radius: 6px;
  padding: 5px;
  cursor: pointer;
  color: var(--text-secondary);
  display: flex;
  align-items: center;
  transition: all 0.12s;
}
.mermaid-close-btn:hover { color: var(--text); background: var(--bg-tertiary); }
.mermaid-popup-body {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  overflow: hidden;
}
.mermaid-popup-content {
  transform-origin: center center;
  transition: transform 0.15s ease;
}
.mermaid-popup-content svg { max-width: none; max-height: none; }

/* ── Footer ── */
.footer {
  margin-top: 3rem;
  padding-top: 1.5rem;
  border-top: 1px solid var(--border-light);
  color: var(--text-muted);
  font-size: 0.8rem;
}
.footer a { color: var(--text-secondary); text-decoration: none; }
.footer a:hover { color: var(--primary); }

/* ── Memo Controls (bottom-right) ── */
.codedocs-memo-controls {
  position: fixed;
  bottom: 24px;
  right: 24px;
  display: flex;
  align-items: center;
  gap: 10px;
  z-index: 100;
}
.codedocs-memo-visibility-btn {
  width: 40px;
  height: 40px;
  border-radius: 50%;
  background: var(--bg-secondary);
  color: var(--text-secondary);
  border: 1px solid var(--border);
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: transform 0.2s, opacity 0.2s;
}
.codedocs-memo-visibility-btn:hover { transform: scale(1.1); }
.codedocs-memo-visibility-btn.off { opacity: 0.4; }
.codedocs-memo-button {
  position: relative;
  width: 56px;
  height: 56px;
  border-radius: 50%;
  background: var(--primary);
  color: white;
  border: none;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: transform 0.2s, box-shadow 0.2s;
}
.codedocs-memo-button:hover {
  transform: scale(1.1);
  box-shadow: 0 6px 16px rgba(0, 0, 0, 0.2);
}
.codedocs-memo-button:active { transform: scale(0.95); }
.codedocs-memo-badge {
  position: absolute;
  top: -4px;
  right: -4px;
  background: #ef4444;
  color: white;
  font-size: 0.75rem;
  font-weight: 700;
  min-width: 20px;
  height: 20px;
  border-radius: 10px;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 0 6px;
  border: 2px solid var(--bg);
}

/* ── Sticky Note ── */
.codedocs-sticky {
  position: absolute;
  min-width: 180px;
  min-height: 120px;
  border-radius: 4px;
  box-shadow: 2px 2px 10px rgba(0,0,0,0.18);
  display: flex;
  flex-direction: column;
  z-index: 50;
  font-size: 0.85rem;
  overflow: hidden;
}
.codedocs-sticky.minimized {
  min-width: auto;
  min-height: auto;
  width: 36px !important;
  height: 36px !important;
  border-radius: 6px;
  cursor: pointer;
  overflow: hidden;
}
.codedocs-sticky-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 4px 6px;
  cursor: move;
  gap: 4px;
  filter: brightness(0.92);
  flex-shrink: 0;
}
.codedocs-sticky-cat-select {
  border: none;
  background: transparent;
  font-size: 0.75rem;
  font-weight: 600;
  color: #333;
  cursor: pointer;
  padding: 2px;
  max-width: 120px;
}
.codedocs-sticky-cat-select:focus { outline: none; }
.codedocs-sticky-header-btns {
  display: flex;
  gap: 2px;
  flex-shrink: 0;
}
.codedocs-sticky-btn {
  background: transparent;
  border: none;
  font-size: 1rem;
  color: #555;
  cursor: pointer;
  width: 22px;
  height: 22px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 4px;
  line-height: 1;
}
.codedocs-sticky-btn:hover { background: rgba(0,0,0,0.1); }
.codedocs-sticky-target {
  border: none;
  border-bottom: 1px dashed rgba(0,0,0,0.2);
  background: transparent;
  padding: 4px 8px;
  font-size: 0.8rem;
  font-weight: 500;
  color: #333;
  flex-shrink: 0;
}
.codedocs-sticky-target:focus { outline: none; border-bottom-color: rgba(0,0,0,0.5); }
.codedocs-sticky-target::placeholder { color: rgba(0,0,0,0.35); }
.codedocs-sticky-content {
  flex: 1;
  border: none;
  background: transparent;
  padding: 6px 8px;
  font-family: inherit;
  font-size: 0.8rem;
  color: #333;
  resize: none;
  line-height: 1.5;
}
.codedocs-sticky-content:focus { outline: none; }
.codedocs-sticky-content::placeholder { color: rgba(0,0,0,0.35); }
.codedocs-sticky-colors {
  display: flex;
  align-items: center;
  gap: 4px;
  padding: 4px 8px;
  flex-shrink: 0;
}
.codedocs-sticky-color-circle {
  width: 16px;
  height: 16px;
  border-radius: 50%;
  cursor: pointer;
  border: 2px solid transparent;
  transition: border-color 0.15s, transform 0.15s;
  box-shadow: 0 0 2px rgba(0,0,0,0.15);
}
.codedocs-sticky-color-circle:hover { transform: scale(1.2); }
.codedocs-sticky-color-circle.active { border-color: #333; }
.codedocs-sticky-resize {
  position: absolute;
  right: 0;
  bottom: 0;
  width: 14px;
  height: 14px;
  cursor: nwse-resize;
  background: linear-gradient(135deg, transparent 50%, rgba(0,0,0,0.15) 50%);
}
.codedocs-sticky-min-tag {
  width: 36px;
  height: 36px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: 700;
  font-size: 1rem;
  color: #333;
  cursor: pointer;
}

/* ── Memo Manager Panel (floating above button) ── */
.codedocs-memo-panel {
  position: fixed;
  bottom: 96px;
  right: 24px;
  width: 380px;
  max-width: 90vw;
  max-height: 60vh;
  background: var(--bg);
  border: 1px solid var(--border);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-md);
  display: flex;
  flex-direction: column;
  z-index: 200;
  animation: memoSlideUp 0.3s ease-out;
}
@keyframes memoSlideUp {
  from { transform: translateY(20px); opacity: 0; }
  to { transform: translateY(0); opacity: 1; }
}
.codedocs-memo-panel-header {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 12px 16px;
  border-bottom: 1px solid var(--border);
  background: var(--bg-secondary);
  border-radius: var(--radius-lg) var(--radius-lg) 0 0;
}
.codedocs-memo-panel-header h3 {
  margin: 0;
  font-size: 1rem;
  font-weight: 600;
  flex-shrink: 0;
}
.codedocs-memo-panel-actions {
  display: flex;
  gap: 4px;
  flex: 1;
  justify-content: flex-end;
}
.codedocs-memo-icon-btn {
  width: 32px;
  height: 32px;
  border-radius: 6px;
  border: 1px solid var(--border);
  background: var(--bg);
  color: var(--text-secondary);
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.15s;
  position: relative;
}
.codedocs-memo-icon-btn:hover {
  background: var(--bg-tertiary);
  color: var(--text);
  border-color: var(--primary);
}
.codedocs-memo-close {
  background: transparent;
  border: none;
  font-size: 1.5rem;
  color: var(--text-secondary);
  cursor: pointer;
  width: 32px;
  height: 32px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 6px;
  transition: background 0.2s;
  flex-shrink: 0;
  margin-left: 4px;
}
.codedocs-memo-close:hover {
  background: var(--bg-tertiary);
  color: var(--text);
}
.codedocs-memo-panel-filters {
  display: flex;
  padding: 8px 12px;
  border-bottom: 1px solid var(--border);
}
.codedocs-memo-toggle-btn {
  padding: 6px 12px;
  background: var(--bg);
  border: 1px solid var(--border);
  border-radius: 16px;
  color: var(--text-secondary);
  font-size: 0.8rem;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.15s;
}
.codedocs-memo-toggle-btn.active {
  background: var(--primary-subtle);
  color: var(--primary);
  border-color: var(--primary);
}
.codedocs-memo-list {
  flex: 1;
  overflow-y: auto;
  padding: 8px;
  display: flex;
  flex-direction: column;
  gap: 6px;
}
.codedocs-memo-empty {
  text-align: center;
  color: var(--text-muted);
  font-size: 0.85rem;
  padding: 1.5rem 0;
}
.codedocs-memo-item {
  display: flex;
  align-items: flex-start;
  gap: 8px;
  padding: 8px;
  background: var(--bg-secondary);
  border: 1px solid var(--border);
  border-radius: 6px;
  cursor: pointer;
  transition: background 0.15s;
}
.codedocs-memo-item:hover { background: var(--bg-tertiary); }
.codedocs-memo-cat-icon {
  width: 24px;
  height: 24px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: 700;
  font-size: 0.9rem;
  color: var(--text-secondary);
  flex-shrink: 0;
  background: var(--bg);
  border-radius: 4px;
}
.codedocs-memo-item-info {
  flex: 1;
  min-width: 0;
}
.codedocs-memo-item-target {
  font-size: 0.8rem;
  font-weight: 600;
  color: var(--text);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.codedocs-memo-item-content {
  font-size: 0.75rem;
  color: var(--text-secondary);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  margin-top: 2px;
}
.codedocs-memo-item-meta {
  font-size: 0.7rem;
  color: var(--text-muted);
  margin-top: 2px;
}

/* ── Context Menu ── */
.codedocs-context-menu {
  position: absolute;
  z-index: 9999;
  background: var(--bg);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  box-shadow: var(--shadow-md);
  min-width: 160px;
  padding: 4px 0;
}
.codedocs-context-menu-item {
  padding: 8px 16px;
  font-size: 0.875rem;
  color: var(--text);
  cursor: pointer;
  transition: background 0.12s;
}
.codedocs-context-menu-item:hover {
  background: var(--primary-subtle);
  color: var(--primary);
}

/* ── Dark mode shadows ── */
[data-theme="dark"] .codedocs-memo-button {
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);
}
[data-theme="dark"] .codedocs-memo-button:hover {
  box-shadow: 0 6px 16px rgba(0, 0, 0, 0.4);
}
[data-theme="dark"] .codedocs-memo-panel {
  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.4);
}
[data-theme="dark"] .codedocs-context-menu {
  box-shadow: 0 3px 6px rgba(0, 0, 0, 0.4);
}
[data-theme="dark"] .codedocs-sticky-cat-select,
[data-theme="dark"] .codedocs-sticky-target,
[data-theme="dark"] .codedocs-sticky-content,
[data-theme="dark"] .codedocs-sticky-btn,
[data-theme="dark"] .codedocs-sticky-min-tag {
  color: #222;
}
[data-theme="dark"] .codedocs-sticky-target::placeholder,
[data-theme="dark"] .codedocs-sticky-content::placeholder {
  color: rgba(0,0,0,0.4);
}
[data-theme="dark"] .codedocs-memo-visibility-btn {
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.3);
}

/* ── Responsive: hide sidebars below 1100px ── */
@media (max-width: 1100px) {
  .toc-sidebar { display: none; }
  .left-sidebar { display: none; }
  .layout { grid-template-columns: 1fr !important; }
  .content { max-width: 100%; }
}

/* ── Responsive: hamburger menu below 768px ── */
@media (max-width: 768px) {
  .mobile-menu-toggle { display: flex; }
  .top-nav {
    display: none;
    position: absolute;
    top: 56px;
    left: 0;
    right: 0;
    background: var(--bg);
    border-bottom: 1px solid var(--border);
    box-shadow: var(--shadow-md);
    padding: 0.5rem;
    z-index: 99;
  }
  .top-nav.open { display: block; }
  .top-nav-list {
    flex-direction: column;
    align-items: stretch;
  }
  .top-nav-link {
    width: 100%;
    padding: 8px 12px;
  }
  .content { padding: 1.25rem 1rem; }
  .header-inner { padding: 0 1rem; }
  .left-sidebar { display: none; }
  .toc-sidebar { display: none; }
  .dashboard { padding: 2rem 1rem; }
  .dashboard-title { font-size: 1.75rem; }
}
`;
}
